//! `inclean init <DIR>` — write a documented starter `inclean.toml` into
//! the given directory. Refuses to overwrite an existing file.

use std::path::PathBuf;

use anyhow::{Context, Result};

use crate::config::discover::CONFIG_FILENAME;

const TEMPLATE: &str = r##"# inclean.toml — generated by `inclean init`
#
# This file configures how inclean rewrites #include paths in this project.
# After editing, run `inclean validate` to check the configuration's
# syntax / structure, then `inclean check` for a dry-run on your sources.
#
# Cheat sheet
# -----------
# Rules form a single-inheritance tree via `extends`; rule names are
# globally unique across all inclean.toml files in the project. The
# matching engine evaluates rules in deepest-config-first / declaration
# order with first-match-wins.
#
# Each rule has five matching layers; only the layers you write override
# the inherited values. The defaults are:
#   paths       = ["**"]
#   extensions  = ["@std.c_extensions", "@std.cpp_extensions"]
#   forms       = ["quote"]
#   match       = ".*"
#   match_resolved (layer 5) is reserved for v2 and rejected if set.
#
# Built-in constants (use via @name in any string list, or in regexes):
#   @std.c_extensions, @std.cpp_extensions
#   @std.c_header_extensions, @std.c_source_extensions
#   @std.cpp_header_extensions, @std.cpp_source_extensions
#   @std.cpp17.system_headers, @std.cpp20.system_headers, ...
#   @std.cpp17.system_headers_or  (regex alternation form)
#
# Placeholders (use in action templates and error messages):
#   ${1} ${2} ...           regex captures from layer 4
#   ${include.text}         the include content (unquoted)
#   ${include.dirname}      dirname of the include text
#   ${include.basename}     basename of the include text
#   ${file.path} ${file.dir} ${file.relpath}
#                           the file being edited (relative to project root)
#   $$                      literal '$'

[project]
# Required. The project root, relative to this file. Sub-configs
# (inclean.toml elsewhere in the tree) MUST NOT declare [project].
root = "."


# ----------------------------------------------------------------------------
# Conventional "base" rule. Other rules `extends = "base"` to inherit
# its values. The values below are the most common shape for a library
# whose internal headers live elsewhere from their canonical include path.
# Uncomment and tailor as needed.
# ----------------------------------------------------------------------------
[[rule]]
name = "base"

# Files this rule operates on. gitignore-style globs, relative to the
# project root. `*` does NOT cross `/`; only `**` does.
# paths = ["src/**", "include/**"]

# After cleanup, every quote-include matched by this rule must resolve
# under one of these directories (relative to the project root). Setting
# this to [] explicitly opts the rule out of validation.
# allowed_include_dirs = ["include"]

# Directories the `auto` action searches when resolving an existing
# #include against the current on-disk layout (preprocessor-style: a
# candidate is <dir>/<include text>).
# original_include_dirs = ["src", "src/internal"]

# Validate angle includes (e.g. <mylib/foo.h>) against allowed_include_dirs
# only when the include content matches one of these regexes. System
# headers like <stdio.h> are skipped by default.
# validate_angle_patterns = ["^mylib/"]

# action defaults to { type = "auto", relative_to = "allowed", form = "quote" }
#
# Other action shapes:
#   action = { type = "rewrite", to = "mylib/${include.text}", form = "quote" }
#   action = { type = "keep" }
#   action = { type = "error",   message = "deprecated, use ..." }


# ----------------------------------------------------------------------------
# Examples (commented out). Uncomment to see them in action.
# ----------------------------------------------------------------------------
# [[rule]]
# name = "deprecated-old-utils"
# extends = "base"
# match = '^old_utils\.h$'
# action = { type = "error", message = "old_utils.h is deprecated; use mylib/utils.h" }
#
# [[rule]]
# name = "namespace-cpp-stdlib"
# extends = "base"
# forms = ["angle"]
# match = "^(@std.cpp17.system_headers_or)$"
# allowed_include_dirs = []         # explicit skip-validation
# action = { type = "keep" }
"##;

pub fn run(dir: PathBuf) -> Result<u8> {
    std::fs::create_dir_all(&dir)
        .with_context(|| format!("ensuring {} exists", dir.display()))?;
    let target = dir.join(CONFIG_FILENAME);
    if target.exists() {
        anyhow::bail!(
            "{} already exists; remove it first or pick a different directory",
            target.display()
        );
    }
    std::fs::write(&target, TEMPLATE)
        .with_context(|| format!("writing {}", target.display()))?;
    println!("wrote {}", target.display());
    println!("next:");
    println!("  edit {} to taste, then run:", target.display());
    println!("    inclean validate {}", dir.display());
    println!("    inclean check {}", dir.display());
    Ok(0)
}
