//! `inclean init <DIR>` — write a documented starter `inclean.toml` into
//! the given directory. Refuses to overwrite an existing file.

use std::path::PathBuf;

use anyhow::{Context, Result};

use crate::config::discover::CONFIG_FILENAME;

/// `#:schema` header injected into the generated file so editors (VS Code's
/// Even Better TOML, Helix, Zed, …) pick up validation and completion. The
/// URL is pinned to the CLI version that wrote the file, so future schema
/// changes don't silently invalidate this config.
const SCHEMA_HEADER: &str = concat!(
    "#:schema https://raw.githubusercontent.com/inaku-Gyan/inclean/v",
    env!("CARGO_PKG_VERSION"),
    "/schemas/inclean.schema.json\n\n",
);

const TEMPLATE: &str = r##"# inclean.toml — generated by `inclean init`
#
# This file configures how inclean rewrites #include paths in this project.
# After editing, run `inclean check --level config` to verify the
# configuration's structure, then `inclean check` for a dry-run on your
# sources (and `inclean check --level rules` for the rule-tree conflict
# check without action evaluation).
#
# Cheat sheet
# -----------
# Rules form a single-inheritance tree via `extends`; rule names are
# globally unique across all inclean.toml files in the project. The
# matching engine evaluates rules in deepest-config-first / declaration
# order with first-match-wins.
#
# Each rule has five matching layers; only the layers you write override
# the inherited values. The defaults are:
#   paths       = ["**"]
#   extensions  = ["@std.c_extensions", "@std.cpp_extensions"]
#   forms       = ["quote"]
#   match       = ".*"
#   match_resolved (layer 5) is unset by default; when present it forces
#     the rule to resolve the include uniquely under original_include_dirs
#     and accepts only files matching its under/match constraints:
#       match_resolved = { under = "src/internal" }
#       match_resolved = { match  = '\.h$' }
#     If two original_include_dirs both contain the include, the rule
#     surfaces a layer-5 ambiguity error so you know to narrow the list.
#
# Built-in constants (use via @name in any string list, or in regexes):
#   @std.c_extensions, @std.cpp_extensions
#   @std.c_header_extensions, @std.c_source_extensions
#   @std.cpp_header_extensions, @std.cpp_source_extensions
#   @std.cpp17.system_headers, @std.cpp20.system_headers, ...
#   @std.cpp17.system_headers_or  (regex alternation form)
#
# Placeholders (use in action templates and error messages):
#   ${1} ${2} ...           regex captures from layer 4
#   ${include.text}         the include content (unquoted)
#   ${include.dirname}      dirname of the include text
#   ${include.basename}     basename of the include text
#   ${file.path} ${file.dir} ${file.relpath}
#                           the file being edited (relative to project root)
#   ${resolved.path} ${resolved.dir} ${resolved.basename}
#                           the layer-5 resolved file (rule must have
#                           match_resolved set, else these error)
#   $$                      literal '$'

[project]
# Required. The project root, relative to this file. Sub-configs
# (inclean.toml elsewhere in the tree) MUST NOT declare [project].
root = "."


# ----------------------------------------------------------------------------
# Conventional "base" rule. Other rules `extends = "base"` to inherit
# its values. The values below are the most common shape for a library
# whose internal headers live elsewhere from their canonical include path.
# Uncomment and tailor as needed.
# ----------------------------------------------------------------------------
[[rule]]
name = "base"

# Files this rule operates on. gitignore-style globs, relative to the
# project root. `*` does NOT cross `/`; only `**` does.
# paths = ["src/**", "include/**"]

# After cleanup, every quote-include matched by this rule must resolve
# under one of these directories (relative to the project root). Setting
# this to [] explicitly opts the rule out of validation.
# allowed_include_dirs = ["include"]

# Directories the `auto` action searches when resolving an existing
# #include against the current on-disk layout (preprocessor-style: a
# candidate is <dir>/<include text>).
# original_include_dirs = ["src", "src/internal"]

# action defaults to { type = "auto", relative_to = "allowed", form = "quote" }
#
# Other action shapes:
#   action = { type = "rewrite", to = "mylib/${include.text}", form = "quote" }
#   action = { type = "keep" }
#   action = { type = "error",   message = "deprecated, use ..." }


# ----------------------------------------------------------------------------
# Examples (commented out). Uncomment to see them in action.
# ----------------------------------------------------------------------------
# [[rule]]
# name = "deprecated-old-utils"
# extends = "base"
# match = '^old_utils\.h$'
# action = { type = "error", message = "old_utils.h is deprecated; use mylib/utils.h" }
#
# [[rule]]
# name = "namespace-cpp-stdlib"
# extends = "base"
# forms = ["angle"]
# match = "^(@std.cpp17.system_headers_or)$"
# allowed_include_dirs = []         # explicit skip-validation
# action = { type = "keep" }
"##;

pub fn run(dir: PathBuf) -> Result<u8> {
    std::fs::create_dir_all(&dir).with_context(|| format!("ensuring {} exists", dir.display()))?;
    let target = dir.join(CONFIG_FILENAME);
    if target.exists() {
        anyhow::bail!(
            "{} already exists; remove it first or pick a different directory",
            target.display()
        );
    }
    let contents = format!("{SCHEMA_HEADER}{TEMPLATE}");
    std::fs::write(&target, contents).with_context(|| format!("writing {}", target.display()))?;
    println!("wrote {}", target.display());
    println!("next:");
    println!("  edit {} to taste, then run:", target.display());
    println!("    inclean check --level config {}", dir.display());
    println!("    inclean check {}", dir.display());
    Ok(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    fn scratch_dir() -> PathBuf {
        static N: AtomicU64 = AtomicU64::new(0);
        let p = std::env::temp_dir().join(format!(
            "inclean-init-{}-{}",
            std::process::id(),
            N.fetch_add(1, Ordering::SeqCst),
        ));
        std::fs::create_dir_all(&p).unwrap();
        p
    }

    #[test]
    fn writes_schema_pinned_to_cli_version() {
        let dir = scratch_dir();
        run(dir.clone()).unwrap();
        let body = std::fs::read_to_string(dir.join(CONFIG_FILENAME)).unwrap();
        let first_line = body.lines().next().expect("file is non-empty");
        assert!(
            first_line
                .starts_with("#:schema https://raw.githubusercontent.com/inaku-Gyan/inclean/v"),
            "unexpected schema directive: {first_line}"
        );
        assert!(
            first_line.contains(env!("CARGO_PKG_VERSION")),
            "schema URL should embed CLI version {}: {first_line}",
            env!("CARGO_PKG_VERSION"),
        );
        assert!(
            first_line.ends_with("/schemas/inclean.schema.json"),
            "schema URL should end with /schemas/inclean.schema.json: {first_line}"
        );
    }
}
