pub const CONFIG_FILENAME: &str = "inclean.toml";

/// Current config schema version.
///
/// This intentionally tracks `CARGO_PKG_VERSION`: each published CLI writes
/// its own version into newly generated configs, even when the schema is
/// compatible with older versions.
pub const CFG_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Current Inclean CLI version.
pub const CLI_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Oldest config schema version this CLI can read.
///
/// Bump this only when the CLI intentionally drops support for configs written
/// by an older schema. It is not a release-version mirror.
pub const MIN_COMPAT_CFG_VERSION: &str = "0.3.0-alpha.3";

/// Oldest CLI version expected to read configs generated by this CLI.
///
/// Bump this only when the generated config format needs features that older
/// CLIs cannot parse or execute correctly. For compatible prerelease bumps,
/// leave it at the first compatible CLI in the release line.
pub const MIN_COMPAT_CLI_VERSION: &str = "0.4.0-alpha.3";

#[cfg(test)]
mod tests {
    use semver::Version;

    use super::*;

    #[test]
    fn version_constants_have_consistent_order() {
        let cfg_version = Version::parse(CFG_VERSION).unwrap();
        let cli_version = Version::parse(CLI_VERSION).unwrap();
        let min_cfg_version = Version::parse(MIN_COMPAT_CFG_VERSION).unwrap();
        let min_cli_version = Version::parse(MIN_COMPAT_CLI_VERSION).unwrap();

        assert_eq!(cfg_version, cli_version);
        assert!(min_cfg_version <= cfg_version);
        assert!(min_cfg_version <= min_cli_version);
        assert!(min_cli_version <= cli_version);
    }
}
